### ISSUE TITLE
Негативный пончик

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#11]
Необходимо модицифицировать существующий спрайт для пончика: убрать конечности и изменить стиль на более устрашающий. В результате должно быть представлено 3 вариации пончика.

**Comment by LadygaPavel** [comment]
Варианты расцветки

![Image](https://github.com/PAD1K/DoNuts/assets/83593908/cae6eae9-1d1c-42f1-b01b-d6b02ff56cb9)



![Image](https://github.com/PAD1K/DoNuts/assets/83593908/0909a800-53af-4159-bf6d-a1c8182a79ed)

 Понял, что сейчас это в принципе не важно, оставляю другой цвет для скинов на будущее

**Comment by LadygaPavel** [comment]
Варианты (Обращать внимание только на лицо, все эффекты на глазировке/теле пончика могу применить к каждому варианту, как и сменить цвета)


![Image](https://github.com/PAD1K/DoNuts/assets/83593908/5157bfd6-5cf3-42c9-8da4-78a2fde348c6)



![Image](https://github.com/PAD1K/DoNuts/assets/83593908/339a5d69-ea56-4cfb-a73d-f30aba708920)



![Image](https://github.com/PAD1K/DoNuts/assets/83593908/63e39c22-5438-47d8-abe2-d2d6d9b33669)


![Image](https://github.com/PAD1K/DoNuts/assets/83593908/f8b955f6-7fa1-4def-a913-396a9ac32f25)

**Comment by HozzyUwU** [comment]
Пончики бомба, пускай **боевой** пока будет второй вариант, а вообще в будущем можно будет реализовать "стадии злости" и добавить переход между состояниями 1->2->4. Третий вариант пока не знаю как вписать, но сам спрайт классный.
