### ISSUE TITLE
Оторванные конечности людей

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#12]
Необходимо создать спрайт, который демонстрирует оторванные конечности людей на поверхности пончика. К конкретному спрайту привязывать спрайт нет необходимости, достаточно соблюдать форму пончика, чтобы в дальнейшем этот спрайт накладывался поверх существующих. В результате должно быть представлено 3 варианта "загрязненности" пончика.

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/6294b8d4-40c0-4560-a2f6-0ba4255d37f5)
