### ISSUE TITLE
Кровь на пончике

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#13]
Необходимо создать спрайт, который демонстрирует кровь людей на поверхности пончика. К конкретному спрайту привязывать спрайт нет необходимости, достаточно соблюдать форму пончика, чтобы в дальнейшем этот спрайт накладывался поверх существующих.

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/9742bb3e-3c5d-4cbc-a9dd-cacf61acc882)
