### ISSUE TITLE
Вариации сдавленности человека

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#15]
На основе #14 необходимо создать спрайты, отображающие 3 варианта сжатия персонажа внутри пончика. Спрайты должны быть реализоываны в таком виде, чтобы их можно было заменить один на другой без каких-либо корректировок,

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/50811a7e-d47d-4380-bcca-8e4248542e45)

Сжатие происходит с 1-3 фрейма

![Image](https://github.com/PAD1K/DoNuts/assets/83593908/a23d6792-a604-47af-a9bd-536d73a444d4)

**Comment by LadygaPavel** [comment]
План такой: Для худого 1-3 кадра, средний 2-3, толстый 2
