### ISSUE TITLE
Бросок объекта

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#2]
Необходимо создать 3D объект на сцене, которорму при нажатии на кнопку будет придаваться сила для полета под углом 45 градусов по стандартной траектории после броска без сопротивления воздуха.

**Comment by Wacko34** [comment]
@HozzyUwU 
Сделал два скрипта (+ один инпутАкшионс от юнити):
1. Input, который обрабатывает нажатия пробела и вызывает MoveController.Throw(Vector3) и передает вектор направления (сейчас значения захаржкожены);
2. MoveController, у которого основной метод Throw(Vector3).

В методе MoveController.Throw(Vector3) я задаю силу при помощи AddForce. Вектор направления раскладываю по осям при помощи синуса и косинуса. Потом вектор направления домножаю на силу, которую подобрал руками. Также использую ForceMode.Acceleration чтобы сила не зависела от массы.
