### ISSUE TITLE
Отображение точки падения

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#20]
Необходимо отображать конечную точку траектории полета объекта. Стоит отображать всю траекторию и создать отметку на земле в месте будущего падения. Траектория должно изменяться в момент модификации силы, направления и угла.

**Comment by Wacko34** [comment]
@HozzyUwU 
Пока что посмотрел видосы:
https://www.youtube.com/watch?v=8mGZBYsSXcQ
https://www.youtube.com/watch?v=p8e4Kpl9b28
https://www.youtube.com/watch?v=zue7-KAnHkg

Понял, что нужно использовать ``LineRenderer`` и просчитывать точки траектории в разные моменты времени.

**Comment by Wacko34** [comment]
@HozzyUwU 
Вчера пытался сделать реализацию. Получилось так себе: какие бы формулы я не использовал, всегда получается просто прямая линия в небо. 
Формулы использовал эти:


![Image](https://github.com/PAD1K/DoNuts/assets/80835973/ceb0f941-b13f-4c50-b951-5e55f27f7fb8)


Скрина нет, потому что я там уже все сломал. Вечером прикреплю

**Comment by Wacko34** [comment]
@HozzyUwU 
Если начальная точка траектории и конечная не касаются земли, то это норм?
![image](https://github.com/PAD1K/DoNuts/assets/80835973/7fa5a707-070a-45cd-8ec4-66dc84f388a8)

Как я понимаю это из-за того, что у меня используется transform.position тела как начальная точка отсчета.

**Comment by Wacko34** [comment]
@HozzyUwU 
Как делал:
1. Сделал empty, на который навесил LineRenderer и скрипт-обработчик scripts/TrajectoryRenderer.cs
2. Внутри скрипта написал метод ``TrajectoryRenderer::ShowTrajectory(Vector3, Vector3)```, который принимает вектор начального положения тела и его скорость
3. Переписал метод ``MoveController::Throw(Vector3)``, чтобы тот задавал телу начальную скорость, а не ускорение или силу
4. Для отрисовки траектории, в векторном виде вычисляется промежуточные точки траектории полета тела, через которые это тело проходит. 
5. Эти точки передаются в LineRenderer::SetPositions(Vector3)

Внешний вид линии никак не менял.

> Траектория должно изменяться в момент модификации силы, направления и угла
От силы не зависит, т.к я теперь придаю начальную скорость телу. Т.к эта скорость является вектором, то она зависит от направления и угла. Таже сама скорость зависит от множителя,  который влияет на ее величину и задается как константа в юнити.

Как это выглядит.
До:
![image](https://github.com/PAD1K/DoNuts/assets/80835973/9d19b094-1a8f-4b05-891e-2f009160d801)

В полете:
![image](https://github.com/PAD1K/DoNuts/assets/80835973/0f11818a-fc13-443d-9390-f73fd35b3d41)

После приземления:
![image](https://github.com/PAD1K/DoNuts/assets/80835973/b845b36b-a788-4bad-86f8-6c2c799c84cf)


Скорость зависит от угла:
![image](https://github.com/PAD1K/DoNuts/assets/80835973/ff56e93f-35ad-4a99-afc7-626ce62f0683)

Скорость зависит от множителя:
![image](https://github.com/PAD1K/DoNuts/assets/80835973/36e95b2c-2f14-4952-8804-534e76a6a70e)

Используемые формулы:
https://www.eduspb.com/node/1669
https://www.yaklass.ru/p/fizika/10-klass/kinematika-materialnoi-tochki-6585327/ravnoperemennoe-dvizhenie-6597997/re-50d2e9e5-75da-41e9-a6a4-a4f39606838d
