### ISSUE TITLE
Выбор направления броска

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#3]
Необходимо добавить поле vector3, которое будет отвечать за направление полета объекта. Должна быть возможность модифицировать это поле в game моде.

**Comment by Wacko34** [comment]
@HozzyUwU 
Сделал direction как SerializeField.
_diretion  является единичным вектором, который задает лишь направление, а дальность броска регулируется в другом скрипте.
Как это работает:

![Image](https://github.com/PAD1K/DoNuts/assets/80835973/04c0931f-c79e-40e5-9c10-76ca7c0721a3)

Прыжок направо:
![Image](https://github.com/PAD1K/DoNuts/assets/80835973/5ad3b7bf-f54b-4c84-a420-d938fbc0751f)

Прыжок налево:
![Image](https://github.com/PAD1K/DoNuts/assets/80835973/a484ca04-ae6b-4863-901a-6efa1f1213ca)

Прыжок вверх:
![Image](https://github.com/PAD1K/DoNuts/assets/80835973/9b925528-0b0b-4621-b8d6-fe1395e48f0a)

Прыжок вдаль от камеры:
![Image](https://github.com/PAD1K/DoNuts/assets/80835973/32b0afe2-2699-4193-a0ef-92dfcee68a9b)
![Image](https://github.com/PAD1K/DoNuts/assets/80835973/1dbdf82c-98db-4b2b-bab9-58306d6fddba)

Прыжок на камеру:
![Image](https://github.com/PAD1K/DoNuts/assets/80835973/443cd10b-0fe1-4210-abae-8a214337f6d5)
