### ISSUE TITLE
Заполнить варианты сдавленности

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#39]
Необходимо создать оставшиеся варианты сдавленности для каждого персонажа #38. Для более жирных моделек добавить более надутые кадры, которые напоминают прыщи.

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/aab120b0-e645-4e63-b6fe-72da6b9c471f)

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/2fc1ec65-e2da-4727-b029-b8f663e4e311)

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/ce015534-4dcd-41fc-b597-70a6fa9e9ee0)

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/b99caaf9-e2eb-4d73-93e1-7e532d06fbb6)
