### ISSUE TITLE
Выбор силы броска

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#4]
Необходимо добавить переменную для контроля силы, которая будет придавать силу объекту при броске. Должна быть возможность изменения этой переменной в game моде.

**Comment by Wacko34** [comment]
@HozzyUwU 
Сделал в задаче по отображению траектории полета. Также к телу прикладывается не сила, а задается начальная скорость. Это нужно для того, чтобы вычислять траекторию. 
Результирующая скорость вычисляется следующим образом:
1. Задается множитель скорости и угол:
![Image](https://github.com/PAD1K/DoNuts/assets/80835973/0f5e1fbe-e34b-4999-91da-31cc80113aaf)
2. Задается направление:
![Image](https://github.com/PAD1K/DoNuts/assets/80835973/20cf3519-d0b0-454c-bb64-9370964dbf0b)
3. Направление проецируется с учетом угла прыжка
4. Вычисляется вектор скорости путем перемножения вектора направления и множителя
5. Скорость задается телу:
```
_rigidbody.AddForce(velocity, ForceMode.VelocityChange);
```
