### ISSUE TITLE
Анимация передвижения

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#42]
Необходимо создать анимацию передвижения  по 4 направлениям (вверх, вниз, вправо, влево) для персонажей каждого вида жирности #38.

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/c2500f9a-485b-4b73-8260-01cf4834a331)

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/577225c0-d9e2-42d2-9c5f-cfef698ee3f2)

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/ead990b1-9280-4b76-8e97-31b81aaa7110)

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/35c0b64d-4f3d-4ff8-a9b0-aa0c1b22bccc)

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/5fefc17f-62e1-49de-8e0a-52aa9a665106)

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/2a474ce3-0cb5-457a-8de5-b536684e1392)

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/b2b86328-0537-4a0c-a847-1bb936422ab3)
