### ISSUE TITLE
UI для управления броском

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#5]
Необходимо реализовать механизм управления направлением и силой броска при использовании пользовательского интерфейса. При "касании и оттягивании в сторону от объекта" курсора должно регулироваться направление броска и его сила, которая должна зависеть от того, насколько далеко от объекта "оттянут" курсор. 
Для выполнения таска стоит использовать [On-screen stick](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.3/manual/OnScreen.html) или [интерфейсы](https://docs.unity3d.com/2018.3/Documentation/ScriptReference/EventSystems.IDragHandler.html), или [рейкасты](https://www.youtube.com/watch?v=HfqRKy5oFDQ).

**Comment by Wacko34** [comment]
@HozzyUwU 
Ну как я понимаю это будет стик в углу экрана.
Т.к у меня есть единичный вектор Vector3 для задания направления, то я так понимаю, что при помощи стика я должен получать направление и передавать его в  X, Z компоненты вектора (т.к Y всегда 1 -- высота прыжка). А удаленность от стика будет изменять множитель вектора скорости. Угол, как я понимаю, всегда остается константой. 

Как сделал в итоге:
Вектор направления задается вектором со стика. Отсюда же берется модуль вектора и он дополнительно домножается на вектор скорости.

Пока не делал PR, т.к договорились, что Артем сделает канвас. Перенесу на него кнопку, но сейчас это выглядит так:
![Image](https://github.com/PAD1K/DoNuts/assets/80835973/1ba98681-5ac5-447e-ace6-89d609762ca9)

![Image](https://github.com/PAD1K/DoNuts/assets/80835973/ab08651f-e306-4c72-83aa-ea77a8b7eed4)

![Image](https://github.com/PAD1K/DoNuts/assets/80835973/d2531a86-1b81-4cc7-87ed-accaefc179b0)

![Image](https://github.com/PAD1K/DoNuts/assets/80835973/4b0a96b1-4956-4088-aa5c-f29b518dd029)

![Image](https://github.com/PAD1K/DoNuts/assets/80835973/dfb6c5fa-0cfa-4c74-81bc-57532e136c12)

![Image](https://github.com/PAD1K/DoNuts/assets/80835973/0eff82bf-d2fc-48c8-9fdb-c1995dfc2c29)

![Image](https://github.com/PAD1K/DoNuts/assets/80835973/f5766d40-9107-4509-8850-3823485f31e8)

(просто на месте прыгнул типа)
![Image](https://github.com/PAD1K/DoNuts/assets/80835973/1da3e415-a425-4895-9d13-f2bb3237da9b)
