### ISSUE TITLE
Контакт с противником

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#62]
Необходимо реализовать модуль, который будет отслеживать коллизию персонажа с объектами типа Enemy.
Требуется создать объект с тэгом Enemy и прикрепить к нему триггер. При коллизии игрока с этим тригером должен вызываться ивент, который в качестве аргумента принимает объект класса противника #63.

**Comment by Wacko34** [comment]
@HozzyUwU 
С Артемом договорились, что он сделает префаб противника и завтра вечером я начну делать
