### ISSUE TITLE
Кровь от пончика

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#82]
Необходимо найти информацию по поводу доступных способов создания крови, будь то спрайты или другие элементы. Цель: в момент бездействия персонажа из него должна вытекать кровь, которую мы видим прямо на земле и ее количество увеличивается со временем. После смены позиции пончика, кровь должна оставаться на своем месте. Минимальным приемлемым вариантом может быть постепенное изменение спрайта персонажа под которым увеличивается лужа крови.

**Comment by LadygaPavel** [comment]
Варианты найдены, пока проблемы с интернетом, поэтому отложил
