### ISSUE TITLE
Idle Donut Animation

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#84]
Необходимо реализовать анимацию, который будет проигрываться в процессе бездействия персонажа.

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/1fdea748-1664-48e4-bb20-c016a7081dd6)

Попутно разбирался с анимацией в юнити и расположением объектов по папкам
