### ISSUE TITLE
Tilemap для земли

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#86]
Необходимо реализовать tile palette для дальнейшего использовать с tilemap в Unity. Процесс создания тайлов стоит начать с разработки нескольких вариантов самого материала и после ревью утвердить один. Tile palette должен включать также объекты декора.

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/10b4325f-5dd3-4867-bae1-9572449a13a1)
