### ISSUE TITLE
Истощение персонажа

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#87]
Так как персонаж будет постепенно терять свою кровь, а вместе с ней и количество здоровья, то необходимо создать несколько видов истощенности персонажа, которые будут демонстрировать его изменения соответствующие тому или иному количеству здоровья.

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/a1c874a5-fb9b-40a1-a6a3-157855636ff4)
