### ISSUE TITLE
Процесс прицеливания

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/DoNuts#88]
Необходимо создать спрайт, который будет демонстрировать состояние пончика в процессе прицеливания.

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/DoNuts/assets/83593908/487f5496-9cf7-4ea3-a787-3a6ffd6ece3c)



![Image](https://github.com/PAD1K/DoNuts/assets/83593908/9e2ef5f7-0e92-4562-8b74-72fbf43e433a)
